shop/blog/urls.py
from django.urls import path
from .views import ProuductList,CategoryList,ProuductDetail

app_name = "blog"
urlpatterns = [
	path('',ProuductList.as_view(),name="home"),
	path('prouduct/<slug:slug>', ProuductDetail.as_view(), name="detail"),
	path('category/<slug:slug>', CategoryList.as_view(), name="category"),
	path('category/<slug:slug>/page/<int:page>', CategoryList.as_view(), name="category"),
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path ,include
from blog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello', views.answer),
    path('',include('blog.urls'))
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/blog/models.py
from django.db import models
from django.utils import timezone

class ProuductManager(models.Manager):
    def published(self):
        return self.filter(status='p')

class CategoryManager(models.Manager):
    def active(self):
        return self.filter(status='True')


# Create your models here.
class Category(models.Model):
    parent = models.ForeignKey('self', default=None, null=True, blank=True, on_delete=models.SET_NULL,
                               related_name='childeren', verbose_name="زیر دسته ")
    title = models.CharField(max_length=200, verbose_name="عنوان  دسته بندی")
    slug = models.SlugField(max_length=100, unique=True, verbose_name="آدرس محصول")
    status = models.BooleanField(default=True, verbose_name="ایا نمایش داده شود؟ ")
    position = models.IntegerField(verbose_name="پوزیشن")

    class Meta:
        verbose_name = "دسته بندی"
        verbose_name_plural = " دسته بندی ها "
        ordering = ['parent__id', 'position']

    def __str__(self):
        return self.title

    objects = CategoryManager()



# Create your models here.
class Prouduct(models.Model):
    STATUS_CHOICES = (
        ('d', 'پیش نویس '),
        ('p', "منتشر شده"),
    )
    name = models.CharField(max_length=200, verbose_name="نام محصول")
    price = models.CharField(max_length=200, verbose_name="قیمت ")
    slug = models.SlugField(max_length=100, unique=True, verbose_name="آدرس ")
    category = models.ManyToManyField(Category, verbose_name="دسته بندی ", related_name="prouducts")
    description = models.TextField(verbose_name="توضیحات ")
    thumbnail = models.ImageField(upload_to="images", verbose_name="تصویر محصول ")
    publish = models.DateTimeField(default=timezone.now, verbose_name=" زمان انتشار")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, verbose_name=" وضعیت")

    class Meta:
        verbose_name = "محصول "
        verbose_name_plural = "محصولات "
        ordering = ['-publish']

    def __str__(self):
        return self.name

    objects = ProuductManager()

shop/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.views.generic import ListView,DetailView
from .models import Prouduct, Category
# Create your views here.

def answer(request):
    return HttpResponse("Hello World")


class ProuductList(ListView):
    template_name = "blog/index.html"
    context_object_name = "prouducts"
    queryset = Prouduct.objects.published()

class ProuductDetail(DetailView):
    def get_object(self):
        slug = self.kwargs.get('slug')
        return get_object_or_404(Prouduct.objects.published(), slug=slug)


class CategoryList(ListView):
    template_name = 'blog/index.html'
    context_object_name = "prouducts"
    def get_queryset(self):
        global category
        slug = self.kwargs.get('slug')
        category = get_object_or_404(Category.objects.active(), slug=slug)
        return category.prouducts.published()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = category
        return context

shop/blog/templates/blog/index.html
{% load static %}
{% load base_tags %}
<!DOCTYPE html>
<html lang="en">
{% block main %}
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>myblog {% block title %}{% endblock %}</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'blog/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'blog/css/shop-homepage.css' %}" rel="stylesheet">
   <link href="{% static 'blog/css/rtl.css' %}" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
     <a class="navbar-brand" href="{% url 'blog:home' %}"> {%title%} </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
{#          <li class="nav-item active">#}
{#            <a class="nav-link" href="{% url 'blog:home' %}">home#}
{#              <span class="sr-only">(current)</span>#}
{#            </a>#}
{#          </li>#}
{#          <li class="nav-item">#}
{#            <a class="nav-link" href="#">About</a>#}
{#          </li>#}
{#          <li class="nav-item">#}
{#            <a class="nav-link" href="#">Services</a>#}
{#          </li>#}
{#          <li class="nav-item">#}
{#            <a class="nav-link" href="#">Contact</a>#}
{#          </li>#}
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">

    <div class="row">

      <div class="col-lg-3">

        <h1 class="my-4">فروشگاه</h1>
        <div class="list-group">
         {% for prouduct in prouducts %}
             {% for cat in prouduct.category.active %}
                    <a class="list-group-item" href="{% url 'blog:category' cat.slug %}">{{cat.title}}</a>
             {% endfor %}
        {% endfor %}
        </div>

      </div>
      <!-- /.col-lg-3 -->

      <div class="col-lg-9">

        <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
          </ol>
          <div class="carousel-inner" role="listbox">
            <div class="carousel-item active">
              <img  class="d-block img-fluid" src="http://placehold.it/900x350" alt="First slide">
            </div>
             <div class="carousel-item ">
              <img  class="d-block img-fluid" src="http://placehold.it/900x350" alt="Second slide">
            </div>
             <div class="carousel-item ">
              <img  class="d-block img-fluid" src="http://placehold.it/900x350" alt="Second slide">
            </div>
{#              {% for prouduct in prouducts %}#}
{#            <div class="carousel-item">#}
{#              <img  class="d-block img-fluid img-size" src="{{prouduct.thumbnail.url}}" alt="Second slide">#}
{#            </div>#}
{#              {% endfor %}#}
          </div>
          <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>

        <div class="row">
        {% for prouduct in prouducts %}
          <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
              <a href="#"><img width=100 height=180 class="card-img-top"  src="{{prouduct.thumbnail.url}}" alt=""></a>
              <div class="card-body">
                <h4 class="card-title">
                  <a href="{% url 'blog:detail' prouduct.slug %}">{{prouduct.name}}</a>
                </h4>
                <h5>{{prouduct.price}} تومان</h5>
              </div>
              <div class="card-footer">
                <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
              </div>
            </div>
          </div>
        {%  endfor  %}
          </div>

        </div>
        <!-- /.row -->

      </div>
      <!-- /.col-lg-9 -->

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2020</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'blog/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'blog/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</body>

</html>
{% endblock %}

shop/blog/templates/blog/prouduct_detail.html
{% load static %}
{% load base_tags %}
<!DOCTYPE html>
<html lang="en">
{% block main %}

{% block title %}
  {{object.title}}
{% endblock %}
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Shop Item - Start Bootstrap Template</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'blog/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'blog/css/shop-homepage.css' %}" rel="stylesheet">
   <link href="{% static 'blog/css/rtl.css' %}" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'blog:home' %}"> {%title%}</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
{#          <li class="nav-item active">#}
{#            <a class="nav-link" href="{% url 'blog:home' %}">خانه#}
{#              <span class="sr-only">(current)</span>#}
{#            </a>#}
{#          </li>#}
{#          <li class="nav-item">#}
{#            <a class="nav-link" href="#">About</a>#}
{#          </li>#}
{#          <li class="nav-item">#}
{#            <a class="nav-link" href="#">Services</a>#}
{#          </li>#}
{#          <li class="nav-item">#}
{#            <a class="nav-link" href="#">Contact</a>#}
{#          </li>#}
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">

    <div class="row">

      <div class="col-lg-3">
        <h1 class="my-4">فروشگاه</h1>
        <div class="list-group">
           {% for cat in object.category.active %}
                <a class="list-group-item" href="{% url 'blog:category' cat.slug %}">{{cat.title}}</a>
           {% endfor %}
        </div>
      </div>
      <!-- /.col-lg-3 -->

      <div class="col-lg-9">

        <div class="card mt-4">
          <img class="card-img-top img-fluid" src="{{object.thumbnail.url}}" alt="">
          <div class="card-body">
            <h3 class="card-title">{{object.name}}</h3>
            <h4>{{object.price}} تومان</h4>
              {% for cat in object.category.active %}
                <a href="{% url 'blog:category' cat.slug %}">#{{cat.title}}</a>
              {% endfor %}
            <span class="text-warning">&#9733; &#9733; &#9733; &#9733; &#9734;</span>
            4.0 stars
          </div>
        </div>
        <!-- /.card -->

        <div class="card card-outline-secondary my-4">
          <div class="card-header">
               توضیحات
          </div>
          <div class="card-body">
            <p>{{object.description}}</p>
            <small class="text-muted">Posted by Anonymous on 3/1/17</small>
            <hr>
            <a href="#" class="btn btn-success">Leave a Review</a>
          </div>
        </div>
        <!-- /.card -->

      </div>
      <!-- /.col-lg-9 -->

    </div>

  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2020</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'blog/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'blog/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>


</body>

</html>
{% endblock %}